USE [RRHH]
GO
/****** Object:  StoredProcedure [dbo].[USP_CA_ACRED_BENEFICIO]    Script Date: 08/04/2021 15:55:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[USP_CA_ACRED_BENEFICIO] @opcion int, @usuario varchar(20)

AS
BEGIN
DECLARE @DTS VARCHAR(200),@lote decimal(5,0),@centro decimal(4,0),@banco varchar(2),@sec int,@usuario_ibs varchar(20)
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	IF @opcion = 0
	BEGIN 
			INSERT dbo.PS_CA_ROL_ACRED_EMPL
		SELECT 99999,
		       CA_FEC_PAGO,
		       CA_MONTO_PG,
		       CA_CTA_ACRE,
		       CA_NUM_EMPL,
		       CA_TP_PAGO,
		       CA_ESTATUS,'',NULL,NULL,NULL,NULL,NULL,NULL
		FROM PPS..PS_CA_ROL_ACRED_EMPL A  --REMPLAZO DE ORACLE..SYSADM
		WHERE CA_TP_PAGO like 'BE%'
		 AND NOT EXISTS (SELECT 1 FROM dbo.PS_CA_ROL_ACRED_EMPL B
								WHERE 99999 = B.CA_COD_COMP
								  AND B.CA_FEC_PAGO = A.CA_FEC_PAGO
								  AND B.CA_MONTO_PG = A.CA_MONTO_PG
								  AND B.CA_CTA_ACRE = A.CA_CTA_ACRE
								  AND B.CA_NUM_EMPL = A.CA_NUM_EMPL
								  AND B.CA_TP_PAGO = A.CA_TP_PAGO ) 
 	   
	END 
	Else
	BEGIN
	--DECLARE @DTS VARCHAR(200),@lote decimal(5,0),@centro decimal(4,0),@banco varchar(2),@sec int,@usuario_ibs varchar(20)
	DELETE FROM dbo.WKINPUT	
	
		SELECT @usuario_ibs = MAX(CA_USUARIO)
		 FROM dbo.PS_CA_ROL_ACRED_EMPL B
			WHERE CA_ESTATUS='P'		
			AND CA_TP_PAGO like 'BE%'
	set @usuario_ibs=upper(@usuario_ibs)	
	select @lote =BTHDIB ,@centro=BTHUBR,@banco=BTHUBK
	 from INTERFACES_BENEFCO.TSILPRU7.CAHCYFILES.CNTRLBTH
	 WHERE BTHUSR=@usuario_ibs
	 	
			/*************DEBITO***********/
		INSERT dbo.WKINPUT		
			SELECT 'T'as WINSTA,0 AS WINRTE,@banco AS	WINOBK,	@centro AS WINOBR,'01' AS	WINBNK,	@centro AS WINBRN,'USD' AS WINCCY,CA_CUENTA_DB AS	WINGLN,0 AS ASWINACC,'DR  '	AS WINTCD, 0 AS	WINVDM,0 AS	WINVDD,0 AS	WINVDY,'BENEFICIOS ASISTENCIA ECONOMIC' AS WINTDS
				,
				   CA_MONTO_PG AS WINDRA,0 AS	WINCR1,0 AS	WINUN1,0 AS	WINCR2,0 AS	WINUN2,0 AS	WINCR3,0 AS	WINUN3,0 AS	WINCR4,0 AS	WINUN4,0 AS	WINMDM,0 AS	WINMDD,0 AS	WINMDY,@lote AS WINKBT,ROW_NUMBER() OVER(ORDER BY CA_NUM_EMPL DESC) AS WINKSQ,
				   0 AS WINPYT,@centro AS WINCCN,1 AS	WINFER,'' AS WINMEF, 0 AS WINNID,0 AS WINTRN,0 AS WINRTN,  month(GETDATE()) AS WINBDM,
				   day(GETDATE()) AS WINBDD,year(GETDATE()) AS WINBDY,0 AS WINTTR,@usuario_ibs AS WINUSO,'' AS WINARF,'' AS	WINMBT,0 AS WINCUN,0 AS WINCKN,'' AS WINSVF,0 AS	WINDRR,
				 CA_MONTO_PG AS WINEQV,0 AS WINACR,0 AS WINCNU,0 AS WINCST,0 AS WINDSQ,0 AS WINIVP,0 AS WINIVB			
			 FROM dbo.PS_CA_ROL_ACRED_EMPL B
			WHERE CA_ESTATUS='P'		
			AND CA_TP_PAGO like 'BE%'
			
		  select @sec=COUNT(1) from dbo.PS_CA_ROL_ACRED_EMPL
			   WHERE CA_ESTATUS='P'		
		  AND CA_TP_PAGO like 'BE%'
		

		/********CREDITO**********/
INSERT dbo.WKINPUT		       		
		SELECT 'T'as WINSTA,0 AS WINRTE,ACMBNK AS WINOBK,@centro AS WINOBR,'01' AS	WINBNK,	ACMBRN AS WINBRN,'USD' AS WINCCY,ACMGLN AS	WINGLN,CA_CTA_ACRE AS WINACC,'CR  ' AS WINTCD, 0 AS	WINVDM,0 AS	WINVDD,0 AS	WINVDY,'BENEFICIOS ASISTENCIA ECONOMIC' AS WINTDS,
		       0 AS WINDRA,CA_MONTO_PG AS WINCR1,0 AS	WINUN1,0 AS	WINCR2,0 AS	WINUN2,0 AS	WINCR3,0 AS	WINUN3,0 AS	WINCR4,0 AS	WINUN4,0 AS	WINMDM,0 AS	WINMDD,0 AS	WINMDY,@lote AS WINKBT,((ROW_NUMBER() OVER(ORDER BY CA_NUM_EMPL DESC)) + @sec) AS WINKSQ,
		       0 AS WINPYT,ACMBRN AS WINCCN,1 AS	WINFER,'' AS WINMEF, 0 AS WINNID,0 AS WINTRN,0 AS WINRTN,  month(GETDATE()) AS WINBDM, 
		       day(GETDATE()) AS WINBDD,year(GETDATE()) AS WINBDY,0 AS WINTTR,@usuario_ibs AS WINUSO,'' AS WINARF,'' AS	WINMBT,ACMCUN AS WINCUN,0 AS WINCKN,'' AS WINSVF,0 AS	WINDRR,
		       CA_MONTO_PG AS WINEQV,0 AS WINACR,0 AS WINCNU,0 AS WINCST,0 AS WINDSQ,0 AS WINIVP,0 AS WINIVB 
				 FROM dbo.PS_CA_ROL_ACRED_EMPL B,(SELECT * FROM OPENQUERY(INTERFACES_BENEFCO,'SELECT ACMACC,ACMBNK,ACMBRN,ACMGLN,ACMCUN FROM CAHCYFILES.ACMST,CAHCYFILES.CUMST WHERE ACMCUN=CUSCUN AND (CUSSTF =''3'' OR ACMUC4=''0004'')  ')) AS ACMST
		WHERE CA_ESTATUS='P'		
		AND CA_TP_PAGO like 'BE%' 
		AND ACMACC = CA_CTA_ACRE
		
     set @sec =@sec * 2
      
      UPDATE WKINPUT
        SET WINSVF = 'Y'
       WHERE WINKSQ = @sec

   INSERT dbo.WKINPUT
		SELECT 'B'as WINSTA,0 AS WINRTE,@banco AS	WINOBK,@centro AS WINBRN,'01' AS	WINBNK,	@centro AS WINOBR,'USD' AS WINCCY,0 AS	WINGLN,0 AS ASWINACC,'' AS WINTCD, 0 AS	WINVDM,0 AS	WINVDD,0 AS	WINVDY,'' AS WINTDS,
		       SUM(CA_MONTO_PG) AS WINDRA,SUM(CA_MONTO_PG) AS WINCR1,0 AS	WINUN1,0 AS	WINCR2,0 AS	WINUN2,0 AS	WINCR3,0 AS	WINUN3,0 AS	WINCR4,0 AS	WINUN4,0 AS	WINMDM,0 AS	WINMDD,0 AS	WINMDY,@lote AS WINKBT,0 AS WINKSQ,
		       0 AS WINPYT,0 AS WINCCN,1 AS	WINFER,'' AS WINMEF, 0 AS WINNID,0 AS WINTRN,0 AS WINRTN,  month(GETDATE()) AS WINBDM,
		       day(GETDATE()) AS WINBDD,year(GETDATE()) AS WINBDY,@sec AS WINTTR,@usuario_ibs AS WINUSO,'A' AS WINARF,'Y' AS WINMBT,0 AS WINCUN,0 AS WINCKN,'Y' AS WINSVF,0 AS	WINDRR,
		       0.00 AS WINEQV,0 AS WINACR,0 AS WINCNU,0 AS WINCST,0 AS WINDSQ,0 AS WINIVP,0 AS WINIVB
		 FROM dbo.PS_CA_ROL_ACRED_EMPL B
		WHERE CA_ESTATUS='P'		
		AND CA_TP_PAGO like 'BE%'
		GROUP BY CA_COD_COMP

	  	INSERT INTERFACES_BENEFCO.TSILPRU7.CAHCYFILES.WKINPUT(WINSTA,WINRTE,WINOBK,WINOBR,WINBNK,WINBRN,WINCCY,WINGLN,WINACC,WINTCD,WINVDM,WINVDD,WINVDY,WINTDS
		,	   WINDRA,WINCR1,WINUN1,WINCR2,WINUN2,WINCR3,WINUN3,WINCR4,WINUN4,WINMDM,WINMDD,WINMDY,WINKBT,WINKSQ,
				   WINPYT,WINCCN,WINFER,WINMEF,WINNID,WINTRN,WINRTN,WINBDM,
				   WINBDD,WINBDY,WINTTR,WINUSO,WINARF,WINMBT,WINCUN,WINCKN,WINSVF,WINDRR,
				   WINEQV,WINACR,WINCNU,WINCST,WINDSQ,WINIVP,WINIVB	)
	     SELECT * FROM dbo.WKINPUT
	     
		 ---Actualizar Estatus de los registros
		 UPDATE dbo.PS_CA_ROL_ACRED_EMPL
		 SET CA_ESTATUS = 'A'
			   WHERE CA_ESTATUS='P'		
		  AND CA_TP_PAGO like 'BE%'
	END
END
